{% set name = "napari-griottes" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_griottes-{{ version }}.tar.gz
  sha256: 7b359f932429d126efda3b0c3a5f34b096bf94c5359c43cfa33cdc0ad0e79d63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - griottes
    - napari
    - networkx
    - numpy
    - pandas
    - python >=3.8

test:
  imports:
    - napari_griottes
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aaristov/napari-griottes
  summary: Create graphs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
